#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    if [ "$1" == "artisan" ]; then
        shift 1
        docker-compose exec \
            php \
            bash -c "cd application && php artisan $@"
    elif [ "$1" == "composer" ]; then
        shift 1
        docker-compose exec \
            php \
            bash -c "cd application && composer"
    elif [ "$1" == "test" ]; then
        shift 1
        docker-compose exec \
            php \
            bash -c "cd application && ./vendor/bin/phpunit $@"
    elif [ "$1" == "up" ]; then
        docker-compose up -d
    elif [ "$1" == "down" ]; then
        docker-compose down
    else
        docker-compose "$@"
    fi
else
    echo "./devtool artisan"
    echo "./devtool composer"
    echo "./devtool test"
    echo "./devtool up"
    echo "./devtool down"
    echo "./devtool build"
fi